services:
  postgres:
    image: postgres:18-alpine
    container_name: projectmanagement-db
    env_file:
      - ./.env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: projectmanagement-api
    env_file:
      - ./.env.example
    build:
      context: ./backend
      dockerfile: Api/Dockerfile
      
    ports:
      - "5115:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
